console.log('Generating swagger file...');

const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    version: '1.0.0',
    title: 'GoDiet - API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3001',
  basePath: '/api',
  consumes: ['application/json'],
  produces: ['application/json'],
  securityDefinitions: {
    api_key: {
      type: 'jwt',
      name: 'authentication jwt',
      in: 'header',
    },
  },
  tags: [
    {
      name: 'Auth',
      description: 'Operations about authentication',
    },
    {
      name: 'Patient',
      description: 'Operations about Patient',
    },
    {
      name: 'Food',
      description: 'Operations about Food',
    },
    {
      name: 'User',
      description: 'Operations about user',
    },
    {
      name: 'Planning Meal',
      description: 'Operations about planning meal',
    },
  ],
  definitions: {
    TUser: {
      email: 'any_email@email.com',
      password: 'any_password',
    },
    TUserCreate: {
      email: 'any_email@email.com',
      password: 'any_password',
      name: 'any_name',
    },
    TUserResponse: {
      name: 'any_name',
      email: 'any_email@email.com',
      id: 'any_id',
      token: 'any_token',
    },
    ErrorFieldResponse: {
      status: 'error',
      message: [
        {
          field: 'email',
          message: 'Invalid e-mail format',
        },
      ],
    },
    TFood: {
      id: 'any_id',
      name: 'any_name',
      categoryName: 'any_category',
      baseUnit: 'any_base',
      baseQty: 100,
      attributes: [
        {
          name: 'any_attribute',
          unit: 'any_unit',
          qty: 100,
        },
      ],
    },
    TCreatePatient: {
      email: 'any_email@email.com',
      name: 'any_name',
      height: 100,
      weight: 100,
      birthDate: 'Mon Nov 27 2023',
      gender: 'MASC',
    },
    TPatient: {
      name: 'any_name',
    },
    TUpdatePatient: {
      email: 'any_email@email.com',
      name: 'any_name',
      height: 100,
      weight: 100,
      birthDate: 'Mon Nov 27 2023',
      gender: 'MASC',
    },
    TCreatePlanningMeal: {
      description: 'any_description',
      meals: [
        {
          name: 'any_name',
          time: 'any_time',
          foods: [
            {
              id: 'any_id',
              name: 'any_name',
              quantity: 100,
              origin: 'TACO',
              calories: 200,
              proteins: 100,
              carb: 100,
              fat: 100,
              baseUnit: 'g',
            },
          ],
        },
      ],
    },
  },
};

const outputFile = './swagger-output.json';
const routes = [
  './src/app/modules/Auth/http/routes/index.ts',
  './src/app/modules/Patient/http/routes/index.ts',
  './src/app/modules/User/http/routes/index.ts',
  './src/app/modules/PlanningMeal/http/routes/index.ts',
  '.src/server/routes/food/index.ts'
];

swaggerAutogen(outputFile, routes, doc);
