const swaggerAutogen = require('swagger-autogen')();

const doc = {
  info: {
    version: '1.0.0',
    title: 'GoDiet - API',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3001',
  basePath: '/api',
  consumes: ['application/json'],
  produces: ['application/json'],
  securityDefinitions: {
    api_key: {
      type: 'jwt',
      name: 'authentication jwt',
      in: 'header',
    },
  },
};

const outputFile = './swagger-output.json';
const routes = ['./src/app/modules/Patient/http/routes/index'];

swaggerAutogen(outputFile, routes, doc);
