name: Pull Request

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Run Typechecking
        run: yarn typecheck

      - name: Run the tests
        run: yarn test:ci

      - name: Run lint
        run: yarn eslint . --fix

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'fix: Run ESLint and fix linting issues across all files'
